### ISSUE TITLE
Unsupported Unicode strings on Windows

### ISSUE THREAD

**Issue by tdjastrzebski** [N0ury/dmm_util#1]
Hi @N0ury, thank you for sharing, so far this is the only piece of code I was able to use to read Fluke 289 stored recordings.
I think it is worthwhile to improve it a bit. First issue below. It seems on Windows input from cmd is Unicode, which is not supported.

```
C:\Temp>python Fluke289.py set contact test.com
Traceback (most recent call last):
  File "Fluke289.py", line 520, in <module>
    switch[sys.argv[1]]()
  File "Fluke289.py", line 79, in do_set
    ser.write(cmd)
  File "C:\Program Files\Python36\lib\site-packages\serial\serialwin32.py", line 308, in write
    data = to_bytes(data)
  File "C:\Program Files\Python36\lib\site-packages\serial\serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: "mpq contact,'test.com'\r"
```

**Comment by N0ury** [comment]
@tdjastrzebski thanks for reporting
Please check if it works now.

**Comment by tdjastrzebski** [comment]
No more Unicode errors.  I was able to remove factory settings and set my own.
time_sync works - very useful! Thank you.
