### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by tdjastrzebski** [N0ury/dmm_util#12]
```
File "dmm_util.py", line 93
    match len(name):
            ^
SyntaxError: invalid syntax
```

**Comment by N0ury** [comment]
What python version do you use?
3.10+ is needed.
I use 3.10.2

**Comment by tdjastrzebski** [comment]
3.6.8 :/ - it may be a good idea to add some initial check and message

**Comment by tdjastrzebski** [comment]
I bet many electronics engines, even they have the latest and greatest Python version, do not know how to import "serial module".
Probably after 5 minutes of Googling most most of will them will give up. I am still Googling.

**Comment by N0ury** [comment]
I have changed the README.
It's not possible to add check, syntax one is done first.
It would be necessary to add a wrapper.
It's much simpler this way

**Comment by tdjastrzebski** [comment]
I did not mean syntax check but Python runtime version check.

**Comment by N0ury** [comment]
I have well understood, but this check **is not** possible.
Python interpreter checks syntax **first**.  It runs the script, and thus the test in a **second time**.
It never gets to that stage.

**Comment by tdjastrzebski** [comment]
I see.
