### ISSUE TITLE
There might be a difference between Fluke firmware 1.16 and newer 1.41; not the same data structure.

### ISSUE THREAD

**Issue by dbbotkin** [N0ury/dmm_util#14]
First, thanks for translating the Ruby code to Python. I am a 'user,' not a professional programmer, and have been working with my Fluke 289 (fw 1.41) to collect voltage measurements from some experiments. Exploring the output from QRSI, I produced a spreadsheet 'Data Dump' to see if I could figure out how to access recording samples directly (FlukeView software is designed for documentation, not calculation). In the process, I could not reconcile the data structure in your code (or the Ruby predecessor) with what was the result of QRSI on my Fluke 289.
[QRSI_ASCII-Data Dump.csv](https://github.com/N0ury/dmm_util/files/8201257/QRSI_ASCII-Data.Dump.csv)

**Comment by dbbotkin** [comment]
Is it possible to confirm the firmware version of the Fluke 289 that was used to develop the Ruby program? Also the one being used to evaluate the Python script  #here?

**Comment by N0ury** [comment]
I don't know if the Ruby program has been developed using a 287 or a 289.
I don't know what firmware it had.
I have asked the developper but I'm not sure I'll have an answer...

I use a 287 with V1.16 firmware.
I think other people here are using this code successfully with a 289 with V1.41 firmware.
I think [tdjastrzebski](https://github.com/tdjastrzebski) does so.

If you could explain a little bit more you csv file...

**Comment by dbbotkin** [comment]
This script:
def QRSI():
    ser.write(('qrsi 14' + '\r').encode('utf-8'))
    ser.read(2) # the OK 0 and CR
    data = (ser.read(999)) #.decode('utf-8'))
    for i in range(0 , len(data)):
        print (str(i)+','+str((data[i])))

Produces a dump of 'Recording' data representing the decimal ASCII for a byte::
0,35
1,48
2,199
3,2
4,0
5,0
6,56
7,136
8,216
9,65
10,0
11,160
12,5
13,229
14,56
15,136
16,216
17,65
18,0
19,176
20,122
21,230
22,0
23,0
24,240
25,63
26,0
27,0
28,0
29,0
30,225
31,122
32,164
33,63
34,123
35,20
36,174
37,71
38,200
39,2
40,0
41,0
42,8
43,0
44,0
45,0
46,3
47,0
48,0
49,0
50,1
51,0
52,1
53,0
54,0
55,0
56,73
57,64
58,0
59,0
60,0
61,0
62,0
63,0
64,1
65,0
66,0
67,0
68,0
69,0
70,0
71,0
72,0
73,0
74,32
75,0
76,0
77,0
78,1
79,0
80,2
81,0
82,124
83,255
84,35
85,64
86,115
87,104
88,145
89,237
90,1
91,0
92,0
93,0
94,3
95,0
96,5
97,0
98,2
99,0
100,0
101,0
102,56
103,136
104,216
105,65
106,0
107,176
108,122
109,230
110,82
111,101
112,99
113,111
114,114
115,100
116,105
117,110
118,103
119,32
120,49
121,57
122,13

This was repeated for each 'Recording" as a column of numbers in the spreadsheet. My first task was to look for differences between columns as "interesting" for analysis. When I found :
"Recording##" and the bytes for the number of samples, I matched the data descriptions into the CONTENTS column.
In the documentation for the Ruby program, the number of Recordings was "0 to 8" and I found "0 to 20" with the 1.41 firmware, so I thought you might want to know.

I was not able to get QSRR to work at all using the Recording IDX and any number in the range of samples for that IDX. Then I realized that it required the "reading_index" from QRSI; now it works. DUH. Hope this helps. I'm concentrating on making a simple script (;-) to print out thousands of measurements to go into DataGraph for analysis. Thanks again for your conversion from Ruby. Ruby and Python are like not ever going to be friends. Ruby is write-only code in my world; I tried to read it, but seeing the # comment character used in an expression was too much.

**Comment by dbbotkin** [comment]
There might be differences in the data structure between Fluke289 meters using fw1.16 and 1.41, however I think Fluke is clever enough to make that a non-issue for users. Using your documentation of the structure, I am able to extract the data I need directly from my meter. Thanks again, if you need any beta testing help, send me a message.
