### ISSUE TITLE
Errors on downloading 100+ data values

### ISSUE THREAD

**Issue by dbbotkin** [N0ury/dmm_util#18]
Some feedback on issues with bulk data transfer. With less than 100 item downloads of VDC floats, done in a few seconds. Over about 120, it throws an error and quits. Block problem probably. For testing, I can initiate a script to download 100 items and repeat by manual 'run' forever with no problem. To download 200+ I have to use 'time.sleep(1') to avoid throwing an error. 

You might want to check your code in 'read_retry'? Or is there a way to slice the data without iterating through samples?

**Comment by dbbotkin** [comment]
For some reason the error occurs at item 113 repeatedly ???!

Traceback (most recent call last):
  File "/Users/donal/Library/Mobile Documents/com~apple~CloudDocs/Documents/Documents - SilverSurfer/Fluke 289 programs/Get_measurement_value.py", line 305, in <module>
    sample = dict(qsrr('553',str(v)))
  File "/Users/donal/Library/Mobile Documents/com~apple~CloudDocs/Documents/Documents - SilverSurfer/Fluke 289 programs/Get_measurement_value.py", line 89, in qsrr
    raise ValueError('By app: Invalid block size: %d should be 146' % (len(res)))
ValueError: By app: Invalid block size: 145 should be 146

**Comment by dbbotkin** [comment]
The "item 113" is **not** consistent across Recordings; there might be a problem in the data?

**Comment by dbbotkin** [comment]
My problem is same as #7

**Comment by N0ury** [comment]
Yes, it's a duplicate.
It should be solved now.
v0.2.9 is in the master branch, and in PyPi.
