### ISSUE TITLE
On a 289, getting multiple recordings do not work. 

### ISSUE THREAD

**Issue by Jaymos1** [N0ury/dmm_util#25]
`python -m fluke_28x_dmm_util -p COM5 get recordings 3, 4 `should be legal according to the instructions:

```
  get recordings {name | index} [, {name | index}...]

  'name' is the name used for a recording, 'index' is a number
  These data can be displayed with 'list' command,
  'name' can be surrounded by quotes in case it contains spaces.
  If this parameter contains only digits, value is assumed to be an index.
  Otherwise, it will be taken as a name. Multiple names or indexes are permitted, they must be comma separated.
```

but it does not work and it brings up the help text.
No combination of multiple numbers from 1 to 7 works.

**Comment by N0ury** [comment]
Not really. Comma separated...but with no spaces...
try with `python -m fluke_28x_dmm_util -p COM5 get recordings 3,4`

**Comment by Jaymos1** [comment]
Ok. Thx.

No hurry. As long as it is listed.

What is the practice here: I suppose you will close the issue after it is done?

**Comment by N0ury** [comment]
Yes, I'll do it

**Comment by N0ury** [comment]
It's done in [commit 18DC193](https://github.com/N0ury/dmm_util/commit/18dc193ca6ac15c88c05fed8af7407281d007bf9)
