### ISSUE TITLE
script does not run

### ISSUE THREAD

**Issue by Jaymos1** [N0ury/dmm_util#4]
Hi

I am trying to connect to my 289 from Windows 10 and I am stuck.
Could you please help me identify what I am doing wrong. I never used Python before.

I installed Python 3.10
I updated pip
I installed pip install pyserial
I added the path to pyserial

```
C:\Users\jaco\Downloads>python3.10 python3_dmm_util.py
  File "C:\Users\jaco\Downloads\python3_dmm_util.py", line 150
    <title>dmm_util/python3_dmm_util.py at master · N0ury/dmm_util · GitHub</title>
                                                  ^
SyntaxError: invalid character '·' (U+00B7)

```

**Comment by N0ury** [comment]
hi @Jaymos1  there's no reason to have this error.
I can run the script with Windows 11 and Python 3.10.
How did you get the script python3_dmm_util.py?
What command did you use?
Can you paste the code somewhere, in pastebin.com for example?

**Comment by Jaymos1** [comment]
Thx for reply.

Following your suspicion of a bad download, I re-did it.
I now used the ZIP download directly from the github page.

That error above is not present anymore, so you must have been right, i.e. bad download.

Now there is a different error:

`python python3_dmm_util.py COM3 info
`
Produces:

```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python python3_dmm_util.py COM3 info
Traceback (most recent call last):
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 518, in <module>
    switch[sys.argv[2]]()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 86, in do_info
    info = id()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 97, in id
    res = meter_command("ID")
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 482, in meter_command
    data = read_retry()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 471, in read_retry
    if data_is_ok(data): return data
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 458, in data_is_ok
    raise ValueError('By app: Error parsing status from meter (status:%c size:%d)' % (data[0], len(data)))
ValueError: By app: Error parsing status from meter (status:0 size:27)

```

**Comment by Jaymos1** [comment]
I use :

```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python
Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

```

**Comment by N0ury** [comment]
This error means that the meter sends a bad response.
I need to debug a little bit, but not sure to succeed.
Can you add the following line to the script (after line 456):
`  print ("%s",data)`

So that it looks like:

```
  # We should now be in OK state
  print ("%s",data) <-- line added
  if not data.startswith(b"0\r"):
    raise ValueError('By app: Error parsing status from meter (status:%c size:%d)' % (data[0], len(data)))

  return len(data) >= 4 and chr(data[-1]) == '\r'
```

Note that there are two (2) spaces before the print statement, this is important in Python.
Run the script again, and post the result.

**Comment by Jaymos1** [comment]
Thanks !!

```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python python3_dmm_util.py COM3 info
%s b'0\x08DLPJ@ 088,T0,40(08000088\x0c'
Traceback (most recent call last):
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 519, in <module>
    switch[sys.argv[2]]()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 86, in do_info
    info = id()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 97, in id
    res = meter_command("ID")
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 483, in meter_command
    data = read_retry()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 472, in read_retry
    if data_is_ok(data): return data
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 459, in data_is_ok
    raise ValueError('By app: Error parsing status from meter (status:%c size:%d)' % (data[0], len(data)))
ValueError: By app: Error parsing status from meter (status:0 size:27)

```

**Comment by N0ury** [comment]
Are you sure the meter is connected to COM3 port?
This doesn't seem to be a FLUKE communication.
Can you check the Windows device manager

**Comment by Jaymos1** [comment]
I am sure COM3 is on the meter.
See tests below.

Device Manager:
![image](https://user-images.githubusercontent.com/100018714/154798087-f8ed1300-f3ad-427f-9f23-568cf0b49fb4.png)



Previous dump was when all normal, and meter is switched on.
I repeat for good measure:
```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python python3_dmm_util.py COM3 info
%s b'0\x08DLTJD 008,T0,00(40000080\x08'
```


With meter switched off:
```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python python3_dmm_util.py COM3 info
Traceback (most recent call last):
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 519, in <module>
    switch[sys.argv[2]]()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 86, in do_info
    info = id()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 97, in id
    res = meter_command("ID")
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 483, in meter_command
    data = read_retry()
  File "C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master\python3_dmm_util.py", line 478, in read_retry
    raise ValueError('By app: Error parsing status from meter, no data')
ValueError: By app: Error parsing status from meter, no data
```



With cable inserted:
```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python -m serial.tools.list_ports
COM3
1 ports found
```

With cable withdrawn:
```
C:\Users\jaco\OneDrive\Documents\Research\Fluke289\dmm_util-master>python -m serial.tools.list_ports
no ports found
```

**Comment by N0ury** [comment]
Maybe it's a new firmware version.
Can you please post the result of `Setup / Meter Info` on the 289.

**Comment by Jaymos1** [comment]
![image](https://user-images.githubusercontent.com/100018714/154798469-49ca6a6e-f5ca-4fbf-83bf-6a711fab6dd5.png)

![image](https://user-images.githubusercontent.com/100018714/154798473-759f7311-3b56-479d-a9ca-ebf98658f227.png)

**Comment by N0ury** [comment]
We have different firmware versions.
You use 1.41/V0.88 on a 289, and I use 1.16/V0.88 on a 287
I've found this (see [here](https://www.fluke.com/en/support/software-downloads/fluke-287-and-289-multimeter-firmware-update))
`Owners of Fluke 287 multimeters with serial number 42700000 or LOWER can update to firmware version 1.16. These multimeters are NOT upgradable to any firmware higher than 1.16.`
My serial is #37720166. So I can't upgrade it.
I'm sorry but I'm pretty sure software have changed after 1.16
I'll add this information in the Readme.md

**Comment by Jaymos1** [comment]
I experimented a lot this afternoon and I am now convinced that my hardware, a real Fluke IR dongle, does not support the required 115200 baud. 

I do not think that the firmware is different in the communications.

**Comment by Jaymos1** [comment]
A quick visit to the Fluke site confirms my problem:

![image](https://user-images.githubusercontent.com/100018714/154806650-6bed2296-fd0e-4a43-9dd9-3b3dc72da535.png)

I have the right hand one, which works on my 189 at 9600 baud. It looses quality of the characters if used on the 289.

I will get a new one ...

**Comment by N0ury** [comment]
These are good news!
If your cable doesn't support 115200 baud you can receive wrong data.

Mine is similar to the one at the right. I use it with a 287.
When I ordered it some years ago, it was the one needed.

**Comment by N0ury** [comment]
I've found the invoice. I've ordered a `FLUKE IR189USB` for my 287.

**Comment by Jaymos1** [comment]
Thanks. I also checked in the mean time and found that I have the correct one - the IR189USB, but reality is that it does not work properly at 115200 baud. I tested it on the 189 (at 9600 baud), and it works fine there. So I must buy another.

Thanks for the assistance today.

**Comment by tdjastrzebski** [comment]
@Jaymos1 Thanks for the info. This is interesting, I found nowhere speed specification for IR189USB. I will test mine with speeds higher than the default 9600.  What can make the difference is this cable revision. Mine has label "Rev. II".  
Note OC4USB does not list any DDM in "compatible products" section - it lists ScopeMeter 120B only. Are you certain OC4USB is compatible with 289?

**Comment by tdjastrzebski** [comment]
Update: I am showing that 289 communicates at 115200 only.

**Comment by Jaymos1** [comment]
I have more strange info. 

Facts:
My cable is not working on the correct speed 115200 (Fluke 125B and 289). 
It works on a lower speed 9600 (on Fluke 189 and 123).

Before I confirmed the speeds, I still thought it was a protocol problem. I noticed that the return strings from the meter  terminates on either x0c and x08 instead of x0d. These broken bits in the characters are due to the electronic signal from the meter to the pc not changing sharply enough causing the bits at that point not to be clear 1, so it is read by pc as 0. Example: sometimes the meter sends binary 00001101 (x0d) but the pc reads the bits as 0000110**0** (x0c) or 00001**0**0**0** (x08).

I then modified your code to accept any of those three terminating characters. Then the "info function" worked say 30% with many incorrect characters. And I noticed the work FLUKE is always 5 characters but always some bits wrong and the letters different. The giveaway was that those 5 letters were always capitals, because the error is "1"s not reading 1, but 0. That gave it away to me that we are sitting with the SAME protocol, but with erroneous bits. 

The MOST interesting thing is that the channel from the pc to the meter works 100% at 115200 baud. The channels are separate electronic circuits, with different input types, being either opto input converting to elec, and the other channel electrical input converting to optical so it is completely understandable that the logic levels are different.

I could use your code to write my name and company and number into the memory of the meter, because the pc sends, and only expects a simple acknowledgement. And my hack gave that acknowledgement, so the code worked. But for nothing else it worked because too many characters were wrong.

**Comment by tdjastrzebski** [comment]
I suspect **revision** of this cable makes a difference. "189" in IR189USB may suggest that the cable was originally developed for lower speed Fluke 189. Probably Fluke had to introduce an upgrade to be able to offer this cable with 289. Note that 289 is officially being sold with IR189USB, not OC4USB. Of course, this is just my theory.

**Comment by Jaymos1** [comment]
I agree with you. I should put an edit on my previous post to say the info is superseded here.

My IR189USB has the Rev. II sticker. Therefore mine is broken.

**Comment by Jaymos1** [comment]
> Note OC4USB does not list any DDM in "compatible products" section - it lists ScopeMeter 120B only. Are you certain OC4USB is compatible with 289?

For clarity on the different units:
OC4USB is meant for 123 and 120B. 
IR189USB is meant for 189 and 287 and 289.

I however have a small 3D printed converter that allows the IR189USB to mechanically fit on the 123 and 125B.

**Comment by N0ury** [comment]
@Jaymos1  have you received the new cable? Does it work well?

**Comment by Jaymos1** [comment]
I ordered my new cable a week ago, and will receive it by Fedex one week from now on 17th March (hopefully). Sending to Africa takes a bit longer maybe ;-)

I will definitely try your code again, and post. 

For interest, I decided to order a Chinese clone cable, not the original, for the reason that it seems that it might be more flexible to modify to fit my 123. https://www.ebay.co.uk/itm/174731721865. I will also post how that goes ;-)

**Comment by Jaymos1** [comment]
I received my cable today and it works perfectly. This proves a few things:

1. This comms software is not buggy.
2. My Fluke firmware is NOT weird
3. My original Rev. 2 Fluke IR189USB cable either never worked on high speed, or broke at some point. The eBay vendor who sold it to me in the UK does not even respond to my enquiry via eBay message and direct email on their web site!!

I ordered a Chinese clone cable because I was still sore from the pain Fluke caused, not working at their elevated price. What convinced me of the Chinese, is that they state that they test each one on a 289 meter. That is all I wanted - no confusion, and a working cable.

![image0](https://user-images.githubusercontent.com/100018714/160458622-d7e4f369-bce2-45f0-948d-a01191cc4d66.jpeg)
![image1](https://user-images.githubusercontent.com/100018714/160458631-74f510f6-7561-42a8-8ec4-60d097bec2fa.jpeg)
It works well.
https://www.ebay.co.uk/itm/174731721865

**Comment by N0ury** [comment]
@Jaymos1  Happy to hear that it works now with the new cable
