### ISSUE TITLE
Retrieval of a specified recording

### ISSUE THREAD

**Issue by tdjastrzebski** [N0ury/dmm_util#5]
Retrieval of a specified recording fails.
```
python python_dmm.py com6 saved_measurements index 0
Command: qsmr 0 failed. Status=2
```
To avoid mistakes it may make more sense to use 1-based index corresponding to indexes listed by DDM.  
Adding an option to list recordings (only) may be a good enhancement.

**Comment by N0ury** [comment]
I have adde a list option for min_max, peak and recordings.
For measurements it's not necessary.
I have uploaded a new version.

Examples:
python python3_dmm_util.py <port> recordings
python python3_dmm_util.py <port> recordings 0
python python3_dmm_util.py <port> recordings 0 1 3 <- list of indexes to show
python python3_dmm_util.py <port> recordings 'name 1' <- record name to display
python python3_dmm_util.py <port> recordings list <- new option (gives a list)

**Comment by tdjastrzebski** [comment]
Thank you, I will test it, albeit I still think 1-based index used by DDM itself would be better. This utility is not for programmers :)
I think the usage info is misleading. I says:
`dmm_util <usb port> recordings [index|name|list] ...`
should be:
`dmm_util <usb port> recordings <index|name>+`
`dmm_util <usb port> recordings list`

**Comment by N0ury** [comment]
I will take a look at the numbering of the records.
Can you please create a new issue for this too.
The goal is to close the issues as we go along.

**Comment by N0ury** [comment]
Done
