### ISSUE TITLE
random download errors

### ISSUE THREAD

**Issue by tdjastrzebski** [N0ury/dmm_util#7]
I often got random `Invalid block size: xxx should be 146` errors. I tried slowing COM down but it seems Fluke 289 supports 115200bps only.  
What seems to help is **timeout increase to 100ms in line 522** - 'invalid block size' errors still happen but noticeably much less frequently. Would it be possible to add some retry loop? - providing that the download can be restarted at a given sample.

**Comment by N0ury** [comment]
I haven't succeeded in reproducing this issue.
I have done a long recording, and I can read data easily.
I've tried this on Windows 11 and MacOS. It worked fine on both.
I'll try again

**Comment by N0ury** [comment]
I have finally succeeded in reproducing this issue.
It should be solved in commit [c92b1b1](https://github.com/N0ury/dmm_util/commit/c92b1b16a1d5e2593059ce53a13940256d3018d4)
I have tried it with a 10k measurements recording. This under Windows, Linux end MacOS.
@tdjastrzebski can you please try it.
Note that it's not yet in PyPi, github only. So you need to clone master repo.
README is **not** up to date.
You can run the utility by:
git clone https://github.com/N0ury/dmm_util.git
cd dmm_util
python -m fluke_28x_dmm_util -p COMx........
You can use:
-s separator (defaults to tab)
-t timeout (defaults to 0.09) Don't put too high value, it would make the download too long

**Comment by N0ury** [comment]
@tdjastrzebski do you think this issue can be closed?

**Comment by tdjastrzebski** [comment]
To my surprise, the latest version works quite reliably. Maybe Python version makes a difference.
As far as I am concerned, this issue can be closed.
