### ISSUE TITLE
download output format

### ISSUE THREAD

**Issue by tdjastrzebski** [N0ury/dmm_util#8]
Please:
1. consider separating output values with TAB characters, rather than white spaces
1. add value/column headers  

TAB separated values can be imported to Excel and other tools more easily.  
Using tabs would allow for treating sample date and time as one field value, rather than two values which, typically, later have to be combined.  
A configurable separator may be an idea for future versions but it is not 'must have'.

**Comment by N0ury** [comment]
Done, please check if it's ok.

**Comment by tdjastrzebski** [comment]
Which branch/commitment I should check?

**Comment by N0ury** [comment]
master branch. I have removed the others.

**Comment by tdjastrzebski** [comment]
I am not showing headers and TAB separators in recordings output of the most recent version.
Am I missing something? File attached
[Fluke-J1.txt](https://github.com/N0ury/dmm_util/files/8116966/Fluke-J1.txt)
.

**Comment by N0ury** [comment]
Wrong version uploaded (too much versions here)...
It should be good now.
Now first line doesn't match this excel format.
What should it contain if kept?

**Comment by tdjastrzebski** [comment]
It gets better but:
1. I consistently get this error after 5th data line is read:
```
Traceback (most recent call last):
  File "Fluke289-K.py", line 573, in <module>
    switch[sys.argv[2]]()
  File "Fluke289-K.py", line 463, in do_recordings
    str(measurement['duration']) + '\t',end=' ')
TypeError: must be str, not int
```
The 6th line contains: `2022-02-16 23:33:17 9.99999999e+37 ADC 9.99999999e+37 ADC 0 ADC 9.99999999e+37 ADC 0 STABLE`
2. There is no header line so the user must guess what each column contains
3. As far as the recording header, I would just keep is as it is.

**Comment by N0ury** [comment]
I have made the necessary corrections

**Comment by tdjastrzebski** [comment]
Now it looks very good :)  
I have a second thought, probably this line could be further improved to be more parser friendly.
`Recording 5 (detail) [2022-02-16 23:33:02 - 2022-02-17 19:50:11] : 5444 measurements`
I think I should contain the same data in same order `recordings list` command returns but with field names. E.g.  
`ordinal 5, name Recording 5, start 2022-02-16 23:33:02, stop 2022-02-17 19:50:11, duration 00:20:17:09, measurements 5444`
Note values are comma separated - it simplifies parsing.
It may make sense to return start/stop date *and duration*. What do you think?
Btw, it is always good to use consistent naming (measurements or samples but not both).

**Comment by N0ury** [comment]
`Btw, it is always good to use consistent naming (measurements or samples but not both).
`
I'm note sure I understand what you mean.
For `recordings`, first line contains the number of `measurements`
In the lines that follow (detail), there is the number of `samples` for each of these`measurements`

Are you talking about this or something else?

For the first line, here's how Flukeview Forms display it (here in french):
<img width="369" alt="Capture d’écran 2022-02-23 à 10 55 36" src="https://user-images.githubusercontent.com/4224717/155296718-065586fa-6e19-4ca0-8167-664a26e5603a.png">

We can therefore consider that it is up to the user to decide how to use them.
So it's ok for the format you mention.

ps: Flukeview Forms displays #samples and # events...

**Comment by tdjastrzebski** [comment]
ic, so samples and measurements are not the same thing.

**Comment by N0ury** [comment]
I think it's finished now with this last commit
Do you confirm?

**Comment by tdjastrzebski** [comment]
`Index 1, name Recording 5, start 2022-02-16 23:33:02, end 2022-02-17 19:50:11, duration 00:20:17:09, measurements 5444`
only `Index` is upper case

`Start Time	Primary		Maximum		Average		Minimum		#samples	Description`
Only `#samples` is lower case, `Description` probably/rather should be `Type`.

I am wondering if type (e.g. ADC) should be repeated 4x after each value (pri/max/min/avg) but maybe it should.

Besides the above I think this tool is in much greater shape and actually very handy.

One major outstanding issue: stability.  

Two possible improvements: 1. configurable list separator, 2. standardized commands options  e.g.  
`dmm_util --help`
`dmm_util show --info --port COM1`
`dmm_util read --measurements --port COM1`
in a similar fashion it is done by [commander](https://github.com/tj/commander.js#readme)

**Comment by tdjastrzebski** [comment]
One more recordings defect I just spotted. Sample line reads:
`16-02-16 23:33:02	2.621	ADC	2.6251	ADC	2.6185	ADC	2.5307	ADC	24	STABLE`
Note that the date is incorrect.

**Comment by N0ury** [comment]
I must be tired, I'm starting to make stupid things.
It's corrected.
